/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Entry = IDL.Record({
  'propertyType' : IDL.Text,
  'totalValue' : IDL.Float64,
  'east' : IDL.Float64,
  'unit' : IDL.Text,
  'west' : IDL.Float64,
  'totalArea' : IDL.Float64,
  'roomsCount' : IDL.Nat,
  'south' : IDL.Float64,
  'north' : IDL.Float64,
  'timestamp' : Time,
  'unitRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'clearEntries' : IDL.Func([], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'propertyType' : IDL.Text,
    'totalValue' : IDL.Float64,
    'east' : IDL.Float64,
    'unit' : IDL.Text,
    'west' : IDL.Float64,
    'totalArea' : IDL.Float64,
    'roomsCount' : IDL.Nat,
    'south' : IDL.Float64,
    'north' : IDL.Float64,
    'timestamp' : Time,
    'unitRate' : IDL.Float64,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'clearEntries' : IDL.Func([], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };