/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'propertyType' : string,
  'totalValue' : number,
  'east' : number,
  'unit' : string,
  'west' : number,
  'totalArea' : number,
  'roomsCount' : bigint,
  'south' : number,
  'north' : number,
  'timestamp' : Time,
  'unitRate' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addEntry' : ActorMethod<
    [
      string,
      number,
      number,
      number,
      number,
      string,
      number,
      bigint,
      number,
      number,
    ],
    bigint
  >,
  'clearEntries' : ActorMethod<[], undefined>,
  'getAllEntries' : ActorMethod<[], Array<Entry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];